receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlphttp/uptrace:
    endpoint: http://host.docker.internal:4000
    headers:
      x-uptrace-api-key: "ut_987fe9ccb07f504afe38ea877e7601b426df9a68c549c03a5509b2c2208db95d"

service:
  pipelines:
    traces:
      receivers:
        - otlp

      processors:
        - batch

      exporters:
        - otlphttp/uptrace